# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Fosforo.py
# Created on: 2021-06-22 16:39:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Fosforo <Fosforo_Mehlich_poly> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Fosforo_Mehlich_poly = arcpy.GetParameterAsText(0)
if Fosforo_Mehlich_poly == '#' or not Fosforo_Mehlich_poly:
    Fosforo_Mehlich_poly = "Fosforo_Mehlich_poly" # provide a default value if unspecified

# Local variables:
arg_poly__2_ = Fosforo_Mehlich_poly
arg_poly__4_ = arg_poly__2_
Abaixo_de_120 = "\"Fbsforo___\" >=0 AND \"Fbsforo___\" <5"
arg_poly__5_ = arg_poly__4_
Identificador_Abaixo_de_120 = "1"
arg_poly = arg_poly__5_
v120___180 = "\"Fbsforo___\" >=5 AND \"Fbsforo___\" <10"
arg_poly__6_ = arg_poly
Identificador_120___180 = "2"
arg_poly__3_ = arg_poly__6_
v180___220 = "\"Fbsforo___\" >=10 AND \"Fbsforo___\" <14"
arg_poly__8_ = arg_poly__3_
Identificador_180__220 = "3"
arg_poly__7_ = arg_poly__8_
v180___220__2_ = "\"Fbsforo___\" >=14 AND \"Fbsforo___\" <16"
arg_poly__9_ = arg_poly__7_
Identificador_180__220__2_ = "4"

# Process: Adicionar campo dis
arcpy.AddField_management(Fosforo_Mehlich_poly, "dis", "SHORT", "2", "", "2", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Selecionar Abaixo de 120
arcpy.SelectLayerByAttribute_management(arg_poly__2_, "NEW_SELECTION", Abaixo_de_120)

# Process: Identificador 1
arcpy.CalculateField_management(arg_poly__4_, "dis", Identificador_Abaixo_de_120, "VB", "")

# Process: Selecionar 120 - 180
arcpy.SelectLayerByAttribute_management(arg_poly__5_, "NEW_SELECTION", v120___180)

# Process: Identificador 2
arcpy.CalculateField_management(arg_poly, "dis", Identificador_120___180, "VB", "")

# Process: Selecionar 180 - 220
arcpy.SelectLayerByAttribute_management(arg_poly__6_, "NEW_SELECTION", v180___220)

# Process: Identificador 3
arcpy.CalculateField_management(arg_poly__3_, "dis", Identificador_180__220, "VB", "")

# Process: Selecionar 180 - 220 (2)
arcpy.SelectLayerByAttribute_management(arg_poly__8_, "NEW_SELECTION", v180___220__2_)

# Process: Identificador 3 (2)
arcpy.CalculateField_management(arg_poly__7_, "dis", Identificador_180__220__2_, "VB", "")

