# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# H+ALCTC.py
# Created on: 2021-06-22 16:45:07.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: H+ALCTC <H_AL_CTC_poly> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
H_AL_CTC_poly = arcpy.GetParameterAsText(0)
if H_AL_CTC_poly == '#' or not H_AL_CTC_poly:
    H_AL_CTC_poly = "H+AL_CTC_poly" # provide a default value if unspecified

# Local variables:
arg_poly__2_ = H_AL_CTC_poly
arg_poly__4_ = arg_poly__2_
Abaixo_de_120 = "\"H_Al_CTC__\" >=6 AND \"H_Al_CTC__\" <25"
arg_poly__5_ = arg_poly__4_
Identificador_Abaixo_de_120 = "1"
arg_poly = arg_poly__5_
v120___180 = "\"H_Al_CTC__\" >=25 AND \"H_Al_CTC__\" <33"
arg_poly__6_ = arg_poly
Identificador_120___180 = "2"
arg_poly__3_ = arg_poly__6_
v180___220 = "\"H_Al_CTC__\" >=33 AND \"H_Al_CTC__\" <36"
arg_poly__8_ = arg_poly__3_
Identificador_180__220 = "3"
arg_poly__7_ = arg_poly__8_
v220___250 = "\"H_Al_CTC__\" >=36 AND \"H_Al_CTC__\" <40"
arg_poly__9_ = arg_poly__7_
Identificador_220___250 = "4"
arg_poly__10_ = arg_poly__9_
v250___300 = "\"H_Al_CTC__\" >=40 AND \"H_Al_CTC__\" <60"
arg_poly__11_ = arg_poly__10_
Identificador_250___300 = "5"
arg_poly__12_ = arg_poly__11_
v300___350 = "\"H_Al_CTC__\" >=60 AND \"H_Al_CTC__\" <70"
arg_poly__13_ = arg_poly__12_
Identificador_300___350 = "6"

# Process: Adicionar campo dis
arcpy.AddField_management(H_AL_CTC_poly, "dis", "SHORT", "2", "", "2", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Selecionar Abaixo de 120
arcpy.SelectLayerByAttribute_management(arg_poly__2_, "NEW_SELECTION", Abaixo_de_120)

# Process: Identificador 1
arcpy.CalculateField_management(arg_poly__4_, "dis", Identificador_Abaixo_de_120, "VB", "")

# Process: Selecionar 120 - 180
arcpy.SelectLayerByAttribute_management(arg_poly__5_, "NEW_SELECTION", v120___180)

# Process: Identificador 2
arcpy.CalculateField_management(arg_poly, "dis", Identificador_120___180, "VB", "")

# Process: Selecionar 180 - 220
arcpy.SelectLayerByAttribute_management(arg_poly__6_, "NEW_SELECTION", v180___220)

# Process: Identificador 3
arcpy.CalculateField_management(arg_poly__3_, "dis", Identificador_180__220, "VB", "")

# Process: Selecionar 220 - 250
arcpy.SelectLayerByAttribute_management(arg_poly__8_, "NEW_SELECTION", v220___250)

# Process: Identificador 4
arcpy.CalculateField_management(arg_poly__7_, "dis", Identificador_220___250, "VB", "")

# Process: Selecionar 250 - 300
arcpy.SelectLayerByAttribute_management(arg_poly__9_, "NEW_SELECTION", v250___300)

# Process: Identificador 5
arcpy.CalculateField_management(arg_poly__10_, "dis", Identificador_250___300, "VB", "")

# Process: Selecionar 300 - 350
arcpy.SelectLayerByAttribute_management(arg_poly__11_, "NEW_SELECTION", v300___350)

# Process: Identificador 6
arcpy.CalculateField_management(arg_poly__12_, "dis", Identificador_300___350, "VB", "")

